openshift/ironic-ipa-downloader

Dockerfile.ocp, get-resource.sh
Only download the RDO image if upstream, also switch
to using ubi8 as a base image as OSP is based on RHEL8.
=> Switch ocp image to use a packaged IPA image

get-resource.sh
It's ok if the cache doesn't have anything.
=> Allow curl on cache URL to fail without being fatal

Dockerfile.ocp
We don't need the deps that rhosp-director-images-ipa pulls in
use rpm to install without them to keep the image size down as
much as possible
=> Install rhosp-director-images-ipa without deps

Dockerfile.ocp
Using dnf download should not pull all the dependencies that we
don't really need.
=> Bug 1798385: Use dnf to download the only package we need

Dockerfile.ocp, build-ipa.sh, get-resource.sh
Provide a way to modify the ipa ramdisk using content from other
RPMs.
We could expand on this to modify, inject, or remove content and
tweak the image as we like.
=> Bug 1798491: Add a way to modify ipa image

build-ipa.sh
The arch of the ramdisk should be determined based on the system we're running on, not hardcoded.
This will fix the issue with the latest failing 4.4 builds.
=> Bug 1804128: Ramdisk arch should not be hardcoded

build-ipa.sh
We already do this in the RHCOS images, it needs to be
don't here so hostnames and IP addresses match.
=> Bug1798272 : DHCPv6 set hostname and predictable hostname

Dockerfile.ocp, build-ipa.sh, get-resource.sh
Backport the Change to set hostnames and make DHCPv6 IDs predictable
This patch also depends on 
- Add a way to build/modify ipa image
and its fix
- Ramdisk arch should not be hardcoded
Finally the 4 commit is backported to simplify conflicts
- Use dnf to download the only package we need
=> bug 1804278: set hostnames and make DHCPv6 IDs predictable

Dockerfile.ocp
With this patch we move all the moving parts of the ipa-ramdisk
creation to a builder and just take what we need from it into the
final image.
This depends on openshift/release#7119
Then we need openshift/ocp-build-data#319 and openshift/ocp-build-data#320
Then we can merge this one.
=> Delegate builder for ipa-ramdisk operations

README.md
OpenShift CI does not periodically rebuild images automatically when new
packages are available. This change is being used to force CI to build
us a new image that has efibootmgr installed.
=> Bug 1841355: Force rebuild of ironic-ipa-downloader image

Dockerfile.ocp, build-ipa.sh
So far we've used a very unreliable hack to modify the ipa-ramdisk
and, for example, install new updated content.
We switch to a different more reliable hack using chroot, which
allows us to trigger native mechanisms (like dependency check)
when installing the updated packages.
To be able to run the installation we need to remove the rpm lock
to prevent the ``BDB0091 DB_VERSION_MISMATCH: Database environment
version mismatch``.
In a normal system, we could this in a different way, for example
running ``dnf clean dbcache``, but doing that in a chroot
environment inside a container will simply raise more problems
related to dnf.
=> Use chroot to modify the ipa-ramdisk

Dockerfile.ocp
The python3-bcrypt library is going to be installed inside the
ipa-ramdisk based on its architecture.
=> Bug 1863390: Fix arch for python3-bcrypt

Dockerfile.ocp, build-ipa.sh, chrooted.sh, get-resource.sh
Move the logic to modify the ipa-ramdisk to the chrooted.sh script
that is executed in a chroot environment.
This allows us to use native commands directly in the ipa-ramdisk
image, like dnf, and exit correctly in case of failures.
Also provide a list of packages installed in the ipa-ramdisk.
=> Bug 1863390: Use dnf to install packages in the ipa ramdisk

Dockerfile.ocp, build-ipa.sh, chrooted.sh, ipa-ramdisk-packages-list.txt
An improvement for testing and customization, moving all the
files we need to install in the ipa-ramdisk to a file and having
dnf read its content.
This allows exotic compositions of sources, like urls and local dirs,
without having to touch the Dockerfile.
=> Bug 1873976: Install packages from file content

chrooted.sh
The hack to set the hostname from the DHCPv6 response ends up breaking dual-stack, where it ought to be leaving the hostname that was set by the DHCPv4 response instead, since that matches what the node will end up with later.
=> Bug 1881182: Only use DHCPv6 hostname if no other hostname was set

Dockerfile.ocp
Updating ironic-ipa-downloader builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ironic-ipa-downloader.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
=> Updating ironic-ipa-downloader builder & base images to be consistent with ART

chrooted.sh
This hack has been applied to OCP 4.7 and it's backported to 4.6 as we're seeing the same issue with SSL failing with ssl.SSLWantReadError
For more info please check https://github.com/eventlet/eventlet/issues/308
(cherry picked from commit f2bde9449e9981abf89d736b32338c1b58e70098)
=> Bug 1899190: Apply hack to eventlet

chrooted.sh
/hold
Fix in 4.7 is happening in IPA packaging not on github, will unhold once its verified
=> bug 1902797: Always set hostname from DHCP6_FQDN_FQDN if set

Dockerfile.ocp
This aligns the ramdisk images with what is present
from RHEL 8.4 and incorporates existing, tested Ironic
components.
Resolves: rhbz#1963204
Signed-off-by: Lon Hohberger <lhh@redhat.com>
=> Bug 1963204: Update IPA ramdisk image for RHEL 8.4

Dockerfile.okd, get-resource.sh
Adds an OKD-specific Dockerfile.
Adapts get-resource.sh to work with pre-provided IPA image from RDO,
which comes without a manifest.
Pulls im some formatting and curl flag changes into get-resource.sh from
upstream.
Restores the TMPDIR initialization missing here in downstream
get-resource.sh.
=> Bug 1995531: Add Support for OKD
